In [14]:
import numpy as np

In [15]:
M = np.load('models/transform_sinkhorn_pr_model.npy')

In [16]:
M

array([[ 1.32152344, -0.52458081,  1.01601316, ..., -0.30559524,
         1.38990984,  0.06964477],
       [-0.47519765,  0.23613895,  0.47571558, ..., -0.20723256,
        -0.87365235, -0.75458207],
       [ 0.92010288, -0.48079518, -0.24016263, ...,  0.39533932,
        -0.7784503 ,  0.41939412],
       ...,
       [ 0.02026085, -0.58524444, -0.59813817, ...,  0.44747764,
         0.09212368, -0.18200538],
       [-1.05432562, -0.05609839,  1.19990601, ...,  0.40267405,
         0.79868131,  0.63857379],
       [ 0.30569625,  0.1107119 ,  1.10169242, ..., -1.47953995,
         0.21829881, -0.62517984]])

In [17]:
np.linalg.det(M)

inf

In [18]:
np.linalg.eig(M)

(array([-1.33325706e+01+2.40342091e+01j, -1.33325706e+01-2.40342091e+01j,
        -1.92027617e+01+1.87119967e+01j, -1.92027617e+01-1.87119967e+01j,
        -2.06815813e+01+1.67207110e+01j, -2.06815813e+01-1.67207110e+01j,
        -2.24528491e+01+1.41461207e+01j, -2.24528491e+01-1.41461207e+01j,
        -2.36559409e+01+1.16103502e+01j, -2.36559409e+01-1.16103502e+01j,
        -2.65807505e+01+2.61586891e+00j, -2.65807505e+01-2.61586891e+00j,
        -2.60961785e+01+4.31619638e+00j, -2.60961785e+01-4.31619638e+00j,
        -2.47652005e+01+6.22816706e+00j, -2.47652005e+01-6.22816706e+00j,
        -2.53505803e+01+3.21123021e+00j, -2.53505803e+01-3.21123021e+00j,
        -1.90121725e+01+1.72863558e+01j, -1.90121725e+01-1.72863558e+01j,
        -2.05275861e+01+1.48228308e+01j, -2.05275861e+01-1.48228308e+01j,
        -1.67607679e+01+1.84139749e+01j, -1.67607679e+01-1.84139749e+01j,
        -2.94855749e+00+2.62997981e+01j, -2.94855749e+00-2.62997981e+01j,
        -1.76555491e+00+2.61769271e+01

In [12]:
U,S,VT = np.linalg.svd(M)

In [13]:
VT

array([[-0.03297816,  0.03138314,  0.02875859, ...,  0.01500272,
        -0.01635962,  0.05067976],
       [ 0.02675361, -0.0052808 ,  0.06619277, ..., -0.03719612,
        -0.02911972,  0.0216819 ],
       [-0.08556605,  0.04769585,  0.00041597, ...,  0.01756344,
         0.00399143,  0.0335624 ],
       ...,
       [ 0.07479625,  0.01965915, -0.02557574, ...,  0.04722846,
        -0.06875994,  0.03910435],
       [ 0.0065956 , -0.04216017,  0.06293989, ...,  0.02532557,
        -0.00741449,  0.02627378],
       [ 0.03060155,  0.01398494, -0.00579279, ...,  0.06366663,
         0.04465553,  0.00525394]])

In [1]:
import os
from config import *
from helpers import *

In [2]:
BASE_DATA_DIR = f'/scratch/korunosk/data'
EMBEDDINGS_DIR = os.path.join(BASE_DATA_DIR, 'BERT_sent')

In [6]:
for dataset_id in DATASET_IDS:
    print(dataset_id)
    
    dataset = load_data(BASE_DATA_DIR, dataset_id, encoded=False)
    
    for topic_id in TOPIC_IDS[dataset_id]:
        print(topic_id)
        
        topic = load_data(os.path.join(EMBEDDINGS_DIR, dataset_id), topic_id, encoded=True)
        document_embs, summary_embs, indices, pyr_scores, summary_ids = extract(topic)

        directory = os.path.join(EMBEDDINGS_DIR, dataset_id, topic_id)

        if not os.path.exists(directory):
            os.makedirs(directory)

        np.save(os.path.join(directory, f'document_embs.npy'), document_embs)

        for i, idx in enumerate(indices):
            np.save(os.path.join(directory, f'summary_{i}_embs.npy'), summary_embs[idx[0]:idx[1]])
        
        
        documents, summaries, indices, pyr_scores, summary_ids = extract(dataset[topic_id])
        
        np.save(os.path.join(directory, f'documents.npy'), documents)

        for i, idx in enumerate(indices):
            np.save(os.path.join(directory, f'summary_{i}.npy'), summaries[idx[0]:idx[1]])

TAC2008
D0841
D0804
D0802
D0809
D0819
D0825
D0828
D0826
D0843
D0829
D0813
D0807
D0812
D0820
D0835
D0823
D0847
D0848
D0810
D0822
D0845
D0844
D0839
D0814
D0824
D0821
D0827
D0846
D0818
D0834
D0805
D0817
D0831
D0815
D0836
D0806
D0808
D0837
D0803
D0830
D0838
D0840
D0842
D0832
D0816
D0801
D0833
D0811
TAC2009
D0919
D0904
D0934
D0928
D0944
D0917
D0926
D0921
D0930
D0907
D0929
D0913
D0920
D0909
D0922
D0935
D0912
D0903
D0927
D0940
D0902
D0925
D0910
D0931
D0943
D0939
D0937
D0933
D0915
D0941
D0911
D0924
D0908
D0932
D0914
D0916
D0905
D0923
D0936
D0938
D0942
D0918
D0901
D0906


In [22]:
from config import *

In [30]:
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

topic_ids = np.array(TOPIC_IDS[DATASET_IDS[0]])

for train_idx, test_idx in kf.split(topic_ids):
    print("TRAIN:", topic_ids[train_idx])
    print("TEST:", topic_ids[test_idx])
    print()

TRAIN: ['D0847' 'D0848' 'D0810' 'D0822' 'D0845' 'D0844' 'D0839' 'D0814' 'D0824'
 'D0821' 'D0827' 'D0846' 'D0818' 'D0834' 'D0805' 'D0817' 'D0831' 'D0815'
 'D0836' 'D0806' 'D0808' 'D0837' 'D0803' 'D0830' 'D0838' 'D0840' 'D0842'
 'D0832' 'D0816' 'D0801' 'D0833' 'D0811']
TEST: ['D0841' 'D0804' 'D0802' 'D0809' 'D0819' 'D0825' 'D0828' 'D0826' 'D0843'
 'D0829' 'D0813' 'D0807' 'D0812' 'D0820' 'D0835' 'D0823']

TRAIN: ['D0841' 'D0804' 'D0802' 'D0809' 'D0819' 'D0825' 'D0828' 'D0826' 'D0843'
 'D0829' 'D0813' 'D0807' 'D0812' 'D0820' 'D0835' 'D0823' 'D0831' 'D0815'
 'D0836' 'D0806' 'D0808' 'D0837' 'D0803' 'D0830' 'D0838' 'D0840' 'D0842'
 'D0832' 'D0816' 'D0801' 'D0833' 'D0811']
TEST: ['D0847' 'D0848' 'D0810' 'D0822' 'D0845' 'D0844' 'D0839' 'D0814' 'D0824'
 'D0821' 'D0827' 'D0846' 'D0818' 'D0834' 'D0805' 'D0817']

TRAIN: ['D0841' 'D0804' 'D0802' 'D0809' 'D0819' 'D0825' 'D0828' 'D0826' 'D0843'
 'D0829' 'D0813' 'D0807' 'D0812' 'D0820' 'D0835' 'D0823' 'D0847' 'D0848'
 'D0810' 'D0822' 'D0845' 'D0844' 'D