In [14]:
import numpy as np

In [15]:
M = np.load('models/transform_sinkhorn_pr_model.npy')

In [16]:
M

array([[ 1.32152344, -0.52458081,  1.01601316, ..., -0.30559524,
         1.38990984,  0.06964477],
       [-0.47519765,  0.23613895,  0.47571558, ..., -0.20723256,
        -0.87365235, -0.75458207],
       [ 0.92010288, -0.48079518, -0.24016263, ...,  0.39533932,
        -0.7784503 ,  0.41939412],
       ...,
       [ 0.02026085, -0.58524444, -0.59813817, ...,  0.44747764,
         0.09212368, -0.18200538],
       [-1.05432562, -0.05609839,  1.19990601, ...,  0.40267405,
         0.79868131,  0.63857379],
       [ 0.30569625,  0.1107119 ,  1.10169242, ..., -1.47953995,
         0.21829881, -0.62517984]])

In [17]:
np.linalg.det(M)

inf

In [18]:
np.linalg.eig(M)

(array([-1.33325706e+01+2.40342091e+01j, -1.33325706e+01-2.40342091e+01j,
        -1.92027617e+01+1.87119967e+01j, -1.92027617e+01-1.87119967e+01j,
        -2.06815813e+01+1.67207110e+01j, -2.06815813e+01-1.67207110e+01j,
        -2.24528491e+01+1.41461207e+01j, -2.24528491e+01-1.41461207e+01j,
        -2.36559409e+01+1.16103502e+01j, -2.36559409e+01-1.16103502e+01j,
        -2.65807505e+01+2.61586891e+00j, -2.65807505e+01-2.61586891e+00j,
        -2.60961785e+01+4.31619638e+00j, -2.60961785e+01-4.31619638e+00j,
        -2.47652005e+01+6.22816706e+00j, -2.47652005e+01-6.22816706e+00j,
        -2.53505803e+01+3.21123021e+00j, -2.53505803e+01-3.21123021e+00j,
        -1.90121725e+01+1.72863558e+01j, -1.90121725e+01-1.72863558e+01j,
        -2.05275861e+01+1.48228308e+01j, -2.05275861e+01-1.48228308e+01j,
        -1.67607679e+01+1.84139749e+01j, -1.67607679e+01-1.84139749e+01j,
        -2.94855749e+00+2.62997981e+01j, -2.94855749e+00-2.62997981e+01j,
        -1.76555491e+00+2.61769271e+01

In [12]:
U,S,VT = np.linalg.svd(M)

In [13]:
VT

array([[-0.03297816,  0.03138314,  0.02875859, ...,  0.01500272,
        -0.01635962,  0.05067976],
       [ 0.02675361, -0.0052808 ,  0.06619277, ..., -0.03719612,
        -0.02911972,  0.0216819 ],
       [-0.08556605,  0.04769585,  0.00041597, ...,  0.01756344,
         0.00399143,  0.0335624 ],
       ...,
       [ 0.07479625,  0.01965915, -0.02557574, ...,  0.04722846,
        -0.06875994,  0.03910435],
       [ 0.0065956 , -0.04216017,  0.06293989, ...,  0.02532557,
        -0.00741449,  0.02627378],
       [ 0.03060155,  0.01398494, -0.00579279, ...,  0.06366663,
         0.04465553,  0.00525394]])